# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: James Hamann
name: James Hamann
email: jameshamann0@gmail.com
description: Software Developer
project_one: Searcher
project_one_description: An iOS/Android App which allows users to search ratings and reviews for TVShows and Movies.
project_one_url: https://github.com/jameshamann/searcher-reactnative
project_one_icon: local_movies

project_two: Jekyll Material Theme
project_two_description: A Jekyll Theme based on Material Design using Materialize, currently being used on this site.
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: web

project_three: Turfy
project_three_description: A group project building an iOS app for location based messaging using XCode, Swift 3 and Firebase.
project_three_url: https://github.com/Lawrence-Dawson/turfy
project_three_icon: location_on

project_four: Pict
project_four_description: An Instagram clone that allows users to comment, as well as like and dislike photos. Built using Ruby on Rails, PostgreSQL, Bootstrap, RSpec and Capybara.
project_four_url: https://github.com/jameshamann/pict
project_button: Github
project_four_icon: photo_camera


github: https://github.com/jameshamann/jekyll-material-theme
medium: https://medium.com



baseurl: / # if your site is located at /blog or /home, enter it here, otherwise leave it as '/'
url: https://jameshamann.com # the url of your site
medium: https://medium.com/@jameshamann/
github:  https://github.com/jameshamann




# Build settings
markdown: kramdown

permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sass-converter
  - jekyll-minifier
