# Site settings
title: James Hamann
email: jameshamann@me.com
url: http://jameshamann.com
description: "I’m a full stack developer, with a background in Music Technology, who enjoys building applications of all types! I have experience in building applications using Ruby, Javascript and Swift 3. Have a look at my projects if you are interested and follow my blog to keep up to date with what I am currently working on."
skills: "Software Developer - Music Producer"
meta_author: Hamann James

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: james

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: James Hamann
  location: Location
  social: Around the Web
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jameshamann
  - title: facebook
    url: https://www.facebook.com/james.hamann.50
  - title: github
    url: http://github.com/jameshamann
  - title: soundcloud
    url: https://soundcloud.com/jameshamann
  - title: music
    url: https://jameshamann.bandcamp.com/
  - title: book
    url: https://medium.com/@jameshamann
  - title: instagram
    url: https://www.instagram.com/jameshamann/

# Postal address (add as many lines as necessary)
address:
  - line: London, United Kingdom

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
